name: free-classrooms-bot-unitn

services:
  free-classrooms-bot:
    build: .
    restart: unless-stopped
    depends_on:
      - mongo
    env_file:
      - path: .env
        required: false
    environment:
      - Database__ConnectionString=mongodb://mongo:27017
      - Bot__BotName=Free Classrooms Bot - UNITN
      - Logging__LogLevel__Default=Warning
      - Logging__LogLevel__Microsoft=Warning
      - Logging__LogLevel__System.Net.Http.HttpClient=Warning
    volumes:
      - ./logs:/app/logs
    mem_limit: 512m
    cpus: '2'

  mongo:
    image: mongo:6.0
    command: ["--quiet"]
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
